### ISSUE TITLE
Camera Intrinsic Parameters

### ISSUE THREAD

**Issue by kongsgard** [3dperceptionlab/therobotrix#1]
Hi, and thanks for making this dataset available!

I want to convert the depth maps into point clouds, and need the camera intrinsic parameters to do so correctly. I couldn't find these in the repository or in the published paper.
Could you add the intrinsic parameters to the readme?

width = 1920
height = 1080
fx (x-axis focal length) = ?
fy (y-axis focal length) = ?
cx (x-axis principle point) = ?
cy (y-axis principle point) = ?

**Comment by PabloMzGz** [comment]
Hi, thank you very much for finding it interesting and for testing it.

As the Field of View (FOV) of the cameras is 90 by default (and for all the images of the dataset), the parameters you are asking for would be:
width = 1920
height = 1080
fx (x-axis focal length) = width/2          [960]
fy (y-axis focal length) = width/2          [960]
cx (x-axis principle point) = width/2          [960]
cy (y-axis principle point) = height/2          [540]

If FOV is not 90º, focal lenght should be computed through:
fx = fy = width / (tan(FOV/2) * 2)
We have used these parameters in post-process scripts in order to project points in world coordinates over the images, and they worked fine. We will add them to documentation.

We would also like to add that, if you want to use the tool in order to generate your own data, you can find an updated version in the UnrealROX repository (https://github.com/3dperceptionlab/unrealrox), more concretely in the experimental branch, where last functionalities have been added. We are still updating it from time to time.

Thank you very much again.

**Comment by kongsgard** [comment]
Thank you for the kind and detailed response!

I will definitely also check out UnrealROX. Thank you for pointing me to the experimental branch.
